### ISSUE TITLE
Font name with space has error

### ISSUE THREAD

**Issue by rubydesign** [jscad-community/jscad-text#3]
So hi, being an old programmer i want to program my 3d, not design it by hand.
And i found jscad, and got v2 to work, even with the font example (by downloading the "font")

Researching jscad fonts led me here (i hope i'm in the right place) and i got the localfont and googlefont cli's to output an svg.
That feels like success, though what do i do with the svg ? The jscad example has some js definition of the fonts outline, not svg ?

As per title, when change the font to what i want "Oleo Script" it does not work**. Neither without space, + instaead of space, and 400 weight (as there is no 300). NOw i understand i could download the ttf and use the localfont example.

So i guess my "issue" is just a ruse, my real question is what to do with the svg, or indeed how to generate the js
(Ps, next question, dare i ask, is how to put a bevel on it)

**UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'files' of undefined
    at selectFont (/home/torsten/jscad-text/googlefont/index.js:30:24)
    at /home/torsten/jscad-text/googlefont/index.js:50:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by rubydesign** [comment]
More research has shown https://gero3.github.io/facetype.js/
that will convert to js , but i dare say not a compatible format.
Still, an interesting tool, just in case you didn't know it.

**Comment by z3dev** [comment]
@rubydesign cool.

it seems to me that you want to make something 3D from the font outlines. did i understand correctly?

if so then i suggest working with the JSCAD website; openjscad.xyz
you can find some examples by clicking on the ? in the upper right.

**Comment by z3dev** [comment]
@rubydesign thanks for the comments. i added a 'Project' section to the README file. I hope that gets you going with JSCAD.

**Comment by rubydesign** [comment]
@z3dev Thanks for the help. I have solved my case outside jscad (three.js), so from my side you can close this issue.

https://rubydesign.fi/3d/index
