### ISSUE TITLE
Enclosed parts of letters dont show

### ISSUE THREAD

**Issue by rubydesign** [jscad-community/jscad-text#4]
When the font is rendered, internal structure goes. 
Sorry about the unclear description, i'll attach a picture.
Basically things like an O or 0 are completely filled.
My (oleo) pic has numbers, but this happens to the A in JSCAD

![Screenshot from 2020-11-09 16-06-06](https://user-images.githubusercontent.com/142157/98551061-8b7b6480-22a5-11eb-8d6f-6a0c15fc056d.png)

**Comment by jbirbal-skydom** [comment]
did you ever find a solution?

**Comment by z3dev** [comment]
Sorry. A little more background is probably required. (I’ll add explanation in the next version.)

This library reads fonts and produces 2D paths. Theses are the outlines of each letter. For letters like A or B, etc. there are several outlines per letter, i.e. outside and inside outlines.

What to do with those outlines is up to the user. There are many use cases.

The Google font example goes one step further, and converts those paths to SVG paths. However, outside and inside paths convert to separate SVG paths. Visually, only the outside paths will shown. Both are black filled paths.

**Comment by rubydesign** [comment]
@jbirbal-skydom I never got this to work and found it easier to use three.js and an STL exporter for my designs.
If you just want a few words you are welcome to use it here https://rubydesign.fi/3d/numbers

Also when I use the scad approach, I use actual scad. (So I'll close this as it not my issue anymore)
